name: 联通App每日任务

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'   # 北京时间11:00
    - cron: '30 3 * * *'  # 北京时间11:30

jobs:
  unicom-tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        pip install requests pycryptodome ntplib
        
    - name: 创建配置文件
      run: |
        # 创建huaji_ltyd文件
        echo "${{ secrets.HUAJI_LTYD }}" > huaji_ltyd
        
        # 安全验证（只显示部分信息）
        echo "配置文件已创建，首行预览:"
        head -n 1 huaji_ltyd | awk -F'#' '{print $1"#"$2"#... [token_online长度:"length($3)"]#... [appid长度:"length($4)"]#"$5}'
        
    - name: 运行联通任务脚本
      run: |
        # 设置多线程（根据账号数量）
        NUM_ACCOUNTS=$(wc -l < huaji_ltyd)
        THREADS=$(( NUM_ACCOUNTS > 5 ? 5 : 1 ))
        
        # 执行脚本
        python 联通_Loader.py --threads $THREADS
        
    - name: 上传日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unicom-logs
        path: |
          *.log
          output.txt
        retention-days: 3
