name: 联通App任务

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    # 每天北京时间11:00运行（UTC时间3:00）
    - cron: '0 3 * * *'

jobs:
  run-lt-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Shanghai  # 设置时区为中国标准时间

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 使用Python 3.10

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests pycryptodome ntplib
        
    - name: 准备环境变量
      env:
        HUAJI_LTYD: ${{ secrets.HUAJI_LTYD }}
      run: |
        # 将环境变量写入文件
        echo "$HUAJI_LTYD" > huaji_ltyd.env
        
        # 调试输出（不显示敏感信息）
        echo "已设置 $(wc -l < huaji_ltyd.env) 个账号配置"
        
    - name: 运行联通任务脚本
      run: |
        # 设置多线程环境（根据账号数量）
        NUM_ACCOUNTS=$(wc -l < huaji_ltyd.env)
        THREADS=$(( NUM_ACCOUNTS > 5 ? 5 : NUM_ACCOUNTS ))  # 最多5个线程
        
        # 运行脚本
        python 联通_Loader.py --threads $THREADS
        
    - name: 上传日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lt-logs
        path: |
          *.log
          *.txt
        retention-days: 7  # 保留7天日志
